language: android
sudo: false
dist: trusty
jdk: oraclejdk8
android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-27.0.3
  - android-27
before_install:
- openssl aes-256-cbc -K $SECURE_KEY -iv $SECURE_IV -in matlink-keystore.jks.enc -out
  matlink-keystore.jks -d
- yes | sdkmanager "platforms;android-27"
install:
- sudo apt-get update && sudo apt-get --assume-yes install zip
- git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
- git fetch --unshallow --tags
before_deploy:
- export VERSION_CODE=`echo $TRAVIS_TAG | cut -d"." -f2`
- export APK_NAME=com.github.yeriomin.yalpstore_$VERSION_CODE.apk
- export OTA_NAME=yalp-store-ota-$VERSION_CODE.zip
- cd app/build/outputs/apk/legacy/release/
- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $TRAVIS_BUILD_DIR/matlink-keystore.jks
  -storepass $SECURE_STOREPASS -keypass $SECURE_KEYPASS app-legacy-release-unsigned.apk
  AndroidKey
- jarsigner -verify app-legacy-release-unsigned.apk
- "$ANDROID_HOME/build-tools/27.0.3/zipalign -v 4 app-legacy-release-unsigned.apk
  $APK_NAME"
- cp $APK_NAME $TRAVIS_BUILD_DIR/yalp-store-ota-zip/YalpStore.apk
- cp $APK_NAME $TRAVIS_BUILD_DIR
- cd $TRAVIS_BUILD_DIR/yalp-store-ota-zip
- zip -r $TRAVIS_BUILD_DIR/$OTA_NAME *
- cd $TRAVIS_BUILD_DIR
notifications:
  email: false
env:
  global:
  - secure: A642iUczJqguoFrK4f5DzPhEoMkYua38ri7un14jaYqAVjHbOPDXVQjL9UOoFNa33wqNv7Tje3aCb3ncb7lj/MWMFlyLBxwQx/wIHPKrC4DiislM9DWbVUU0sDVPbQj/s8x0xugVN1Fx/NqzlbOh+jnAeIzGfw3jJKVADzc/A+lqe2MOxX3S4GaDCxwuD/PcISu8PnFN+FPCjiBTp/Cq2qDjALZpM4Hg6nw+ZojyvkCr/IT/frKAXjjdu21Uge0d7G8dRdsJ9ibG1XYwVKPsAtjwzuwmK7iXCk+WJLlYce8IEjiJwO9L1wutBIobDX0v6Pm83V95ar4+wau8Q9rWGkwINZai5Te7Cuk9nRof8aEynUeg//jI5m7WbPKCMn18cgxSV6vUUIPE/idnZ0lKgbv7l7f6niDsrMUIWakWTlcRicoye2ZoqLi9Mdw0v0GqtwNlKTHyIfu06d0RpUKNF5s6aHDvQC3mNOWJJGv2FNcpzVVtEC190rLjwe7dm5Tr2gAREADVj+naeGHfpm8SHXUaw2TmgVi1gV+KVm1TFO51cZmmQ15/T3uNWvqDGjiq1+A0KzGGPVNJzKsKXwyeX6URVW8RPKPHSd15P/HYJClf7Xo0v/HwEcoD3qwQ1g4Az3IOxZRkRpvUcl9oMJR1zunu9xFHmBYJnNgOeW/9vNY=
  - secure: Q+lgvP+bdM+Sx+u4mEoi3nplx1i5wNPC04o+ril5EU9uzK+QEFlhsQGTA5do+gWafA73HeouaOodYY/Xg4vw44yXNDoVss8tcbPAc0RcDKhZbj4LWD/Q051HIGiu8C120EwvYFWgHAiocDFI0dYTzm9LuwUGk0LmmYM+VXQDtH1U33pFZXcoA/RtgwLjyglVHJROQ8axgp4nHluOQmQjv3AhppaxKPNkoIXgGP0rPN9zQQ2emRg1quhqG9UtYPJzkNBAmFFmNd3DOn9S+Ez5nTzKXvI7iEdIpjQgr83BitU2bFXuq+TLH4HtcQqMxKXtR6UdeVE68IwD2zm+ygeMBlk3qmjDySeg3QDx4gsYREPL/1JtdfefOa59fUXlqLEEGcU9Vd+IK5UBqWWUZWzC52M02WeC662bh3GZSvMh4HyM9L5D6W82VN8xNFMs40ME+dArjm1WJ4MA3o2xgubnVFCz8Vl2EoEAqvrkXbmf0qTtsVsGWo+43yKEKdeGk7vI37od3mPNru1Nm0bREL4iapuaJMCKaYEqV15zMOcVf9835m1ykwj/oJZgTfTpLgK7CDz3qfbxE6jwiKrd/+JmzU9Xyw7mwzejkrTQbQo1Pl57P5kuHFt9goUD5Ll04iIjHN5qMrqxUv1kUZOGi6a49b79GOEqPd+yhuLkIggDfBw=
  - secure: E+r5WWol4Hy1Ipjy1o9LtYMmjYJJ7T422fT8GUgybvpSp5V85+hVasf2mTjNXzXTuwVuUVmoAl7oW+cg2nu+y3IZZVZNwyEBv6F4imN86vrKSSsfnCcIDvI5JCQL7zTNoaaDvE89EUtPZOMvDXaFx64qT5FdYudsULKUpivuuXbXtZIVW/Y7v+H22hXOEv9z95wCfhQc1c8mk0Gl2Gq5RubX5bJcVtq7TmvLep00sdphbuwHcO1aSkVi5HS4omvfwX2tfZJSHnTYkyklrofRJ+AYgl/HH0tbrFqyrNlGr0YRnAjkRmXZFa3WC/EMdedobk4Tuv0YjamjiXNery6b3eiBvBb+8c9Uqy63xDl/fXDYoRlMQxI01hvrAHrqPTENpNfVN6cxKsem6lnJekcFSw5sy8n9FIoN/7owOkOV43hoSThnHHpC/hOigvHsBFee/9vXUfzFuZKkZyGIb1/4K0Mkqbk0p7dAtE9b/Nf3oc8J6bYD5IyfaYYebu46GWHueUTf5+IzaNDnfuZg/X4CJ/LhhwOET0UDNDYxXYFANHtyFxE3onlxvk0E7vyaB3Mqb2LRwxRT/A3/sp6/5oQnPTrKd+s7IviKq7kasJhkW0Dn/HpAP2gsZUw7IGWfMG0+/dioTF6Qp3Iwuaw9RpzubOP224mBZbvRVwaR46es5G4=
  - secure: E+LZMmGnLD0149eso5BiGAIXTfsYRkl8rmELhBPwSZOeInli+HipQ4DlcOxW6lmj/anz9hUKxAnKS9GgKR161Kzk+D598ZZsbFqWHTz/6dDMGk1T+nrSG6iH3eRIkaDBzTXlznGmAqOgETkMtKHRMPhNvIssTcRNhAoV85OifR0rUi7Hj7u/CB45fOL269PXwJtVixDxkNQPImkR1FJyO8zD2+VUvdvVuRajqBb1Yc9nCkzlt3EkM+nea2WOx4jyVLIITHGjBC5/yzHvNF5sy9Fl5ZlXdFfqrcXr2Ne7pA4oTgmEqzDlUUY/+L8O/K43L0TEhZjqw7ODs4hYJu/tdHqC3+8OLLzh3IGt0MBTY3e7f1w9WuTqqlyRiM+JQTb5XfyYq8+qSJzaRbsQYtUFMIpfO/ziw2sfqxDjxTSWxP6aDDzIsOxuboNhTHfn4zTHE9s2+Dp9b60+bgXh3szY5J6Zl5cwwEC8gBCDI3tcBsOhdq8RZ0Cnzuj6RBjY8AsmrefT+ynn2ZinKN8ihrvn6y7wLoo5jYXhNrw1HLo689LoGRLWi5/b5Ji3RO2Qs9tySYJux3iG9fWx4yCqLbMILShCrp7RH/axeh1EK6pj8bOkuzDNwIONTBbi/172tGGbn/4yYdAiGbS3lANwuRnlHFuMbw7Io2qpdBPPRae4Xyw=
