language: android
sudo: false
dist: trusty
jdk: oraclejdk8
android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-28
before_install:
  - openssl aes-256-cbc -K $encrypted_607f032c80d7_key -iv $encrypted_607f032c80d7_iv
    -in matlink-keystore.jks.enc -out matlink-keystore.jks -d
  - yes | sdkmanager "platforms;android-28"
install:
- sudo apt-get update && sudo apt-get --assume-yes install zip
- git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
- git fetch --unshallow --tags
before_deploy:
- export VERSION_CODE=`echo $TRAVIS_TAG | cut -d"." -f2`
- export APK_NAME=com.github.yeriomin.yalpstore_$VERSION_CODE.apk
- export APK_NAME_CONTEMPORARY=com.github.yeriomin.yalpstore_contemporary_$VERSION_CODE.apk
- export OTA_NAME=yalp-store-ota-$VERSION_CODE.zip
- export GIT_DIR=$(pwd)
- cd $GIT_DIR/app/build/outputs/apk/legacy/release/
- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $TRAVIS_BUILD_DIR/matlink-keystore.jks
  -storepass $SECURE_STOREPASS -keypass $SECURE_KEYPASS app-legacy-release-unsigned.apk
  matlink
- jarsigner -verify app-legacy-release-unsigned.apk
- "$ANDROID_HOME/build-tools/28.0.3/zipalign -v 4 app-legacy-release-unsigned.apk
  $APK_NAME"
- cp $APK_NAME $TRAVIS_BUILD_DIR/yalp-store-ota-zip/YalpStore.apk
- cp $APK_NAME $TRAVIS_BUILD_DIR
- cd $GIT_DIR/app/build/outputs/apk/contemporary/release/
- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $TRAVIS_BUILD_DIR/matlink-keystore.jks
  -storepass $SECURE_STOREPASS -keypass $SECURE_KEYPASS app-contemporary-release-unsigned.apk
  matlink
- jarsigner -verify app-contemporary-release-unsigned.apk
- "$ANDROID_HOME/build-tools/28.0.3/zipalign -v 4 app-contemporary-release-unsigned.apk
  $APK_NAME_CONTEMPORARY"
- cp $APK_NAME_CONTEMPORARY $TRAVIS_BUILD_DIR
- cd $TRAVIS_BUILD_DIR/yalp-store-ota-zip
- zip -r $TRAVIS_BUILD_DIR/$OTA_NAME *
- cd $TRAVIS_BUILD_DIR
notifications:
  email: false
env:
  global:
  - secure: E+r5WWol4Hy1Ipjy1o9LtYMmjYJJ7T422fT8GUgybvpSp5V85+hVasf2mTjNXzXTuwVuUVmoAl7oW+cg2nu+y3IZZVZNwyEBv6F4imN86vrKSSsfnCcIDvI5JCQL7zTNoaaDvE89EUtPZOMvDXaFx64qT5FdYudsULKUpivuuXbXtZIVW/Y7v+H22hXOEv9z95wCfhQc1c8mk0Gl2Gq5RubX5bJcVtq7TmvLep00sdphbuwHcO1aSkVi5HS4omvfwX2tfZJSHnTYkyklrofRJ+AYgl/HH0tbrFqyrNlGr0YRnAjkRmXZFa3WC/EMdedobk4Tuv0YjamjiXNery6b3eiBvBb+8c9Uqy63xDl/fXDYoRlMQxI01hvrAHrqPTENpNfVN6cxKsem6lnJekcFSw5sy8n9FIoN/7owOkOV43hoSThnHHpC/hOigvHsBFee/9vXUfzFuZKkZyGIb1/4K0Mkqbk0p7dAtE9b/Nf3oc8J6bYD5IyfaYYebu46GWHueUTf5+IzaNDnfuZg/X4CJ/LhhwOET0UDNDYxXYFANHtyFxE3onlxvk0E7vyaB3Mqb2LRwxRT/A3/sp6/5oQnPTrKd+s7IviKq7kasJhkW0Dn/HpAP2gsZUw7IGWfMG0+/dioTF6Qp3Iwuaw9RpzubOP224mBZbvRVwaR46es5G4=
  - secure: E+LZMmGnLD0149eso5BiGAIXTfsYRkl8rmELhBPwSZOeInli+HipQ4DlcOxW6lmj/anz9hUKxAnKS9GgKR161Kzk+D598ZZsbFqWHTz/6dDMGk1T+nrSG6iH3eRIkaDBzTXlznGmAqOgETkMtKHRMPhNvIssTcRNhAoV85OifR0rUi7Hj7u/CB45fOL269PXwJtVixDxkNQPImkR1FJyO8zD2+VUvdvVuRajqBb1Yc9nCkzlt3EkM+nea2WOx4jyVLIITHGjBC5/yzHvNF5sy9Fl5ZlXdFfqrcXr2Ne7pA4oTgmEqzDlUUY/+L8O/K43L0TEhZjqw7ODs4hYJu/tdHqC3+8OLLzh3IGt0MBTY3e7f1w9WuTqqlyRiM+JQTb5XfyYq8+qSJzaRbsQYtUFMIpfO/ziw2sfqxDjxTSWxP6aDDzIsOxuboNhTHfn4zTHE9s2+Dp9b60+bgXh3szY5J6Zl5cwwEC8gBCDI3tcBsOhdq8RZ0Cnzuj6RBjY8AsmrefT+ynn2ZinKN8ihrvn6y7wLoo5jYXhNrw1HLo689LoGRLWi5/b5Ji3RO2Qs9tySYJux3iG9fWx4yCqLbMILShCrp7RH/axeh1EK6pj8bOkuzDNwIONTBbi/172tGGbn/4yYdAiGbS3lANwuRnlHFuMbw7Io2qpdBPPRae4Xyw=
deploy:
  provider: releases
  api_key:
    secure: iJ2Ylzt7/eO+JCdfLNQK89ksBDJ4HyWAgpYsdNXoCrtVoA1eD8Rj7ZPqQsS7OuUcskbQfYC4aRgew67z6hHAKqi3WbuYCuiNMroXJ+Dqu+UMVuWneTcdUnk9wS8WZOPzbuvWEj5tOmOZOIyB7qHqfuWIUlqKAW0ukQw34+/2NLKihyU7/sZ64dOGm6CVFwsSllUUow8XKqa6KObJ1BH4ZP0iQxlzEEBdIF2LamDVTY9Bbz2NBu3qKSMT+LguHUJMOFyw2JqlKunmiZS6RXXiAuFwW+rDsF6aQG1VGSixOk1xCLlPSn8cwrazq0OBywvGGzwVMOawpsjn71OneuAnnqu+vXhhvvCMgnn8iRvdCNeLSZNEFwBHCVMRrEvvbt7IADmGW+jeHpT7u0eTosjaB2qf2l8GSoH2XVUf9HopzrS5sK7xEPgaA9ravHA0/+E4y1T34+nSurp3qsfJweXMYjaGAt5qiCwzfZ2y8bGQ/bqfyJa1Ye5HMwO0tb0nvH0g8ZGp4t49Hr0GHfILkhDHrwTkex6wzL0Aed/eSAfR/xo5wxh9y+bH9NFZLUxV9aLpVowczdK90tSjC60nfURd3EXB/jDfqrOvpae3jCHu+jdX5UUjHbweA9qtOPqzLZwNMEnw7hb3+qGioUrs002eDDxDSVgxUJZX4dnmZciko0Y=
  file:
    - $OTA_NAME
    - $APK_NAME
    - $APK_NAME_CONTEMPORARY
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: matlink/YalpStore
